export type PacienteDto = {
  id: number
  cartaoSus: string
  nome: string
  nomeSocial: string
  nomeMae: string
  nomePai: string
  dataNascimento: string
  sexo: string
  idOrientacaoSexual: number
  idGenero: number
  idNacionalidade: number
  idNaturalidade: number
  ocupacao: string
  cpf: string
  rg: string
  dataEmissao: string
  orgaoEmissor: string
  escolaridade: number
  cep: string
  logradouro: string
  numero: string
  complemento: string
  bairro: string
  idMunicipio: number
  idUf: number
  foneResidencial: string
  foneCelular: string
  foneContato: string
  contato: string
  email: string
  situacao: Boolean
  idModalidade: number
  dataCriacao: string
  latitude: number
  longitude: number
  idSap: number
  idPacienteCorrespondenteDim: number
  idTipoSanguineo: string
  idRaca: number
  numeroProntuario: string
  numeroProntuarioCnes: string
  falecido: boolean
  idAtencaoContinuada: string
  idEstabelecimentoCadastro: number
  apelido: string
  observacao: string
  historiaProgressaFamiliar: string
  foto: string
  necessidadeEspeciais: boolean
  reeducando: boolean
  gestante: boolean
  aleitamentoMaterno: string
  dumDaGestante: string
  idadeGestacional: number
  stGravidezPlanejada: boolean
  nuGestasPrevias: number
  nuPartos: number
}
